USE BAITAP5

--------------------- STORED PROCEDURE ----------
-- CAU 1: LIET KE DS KH(TENKH,DC)CO DAT HANG VAO NGAY THANG NAM X
CREATE PROC CAU1
@X DATETIME
AS
	SELECT TENKH,DIACHI
	FROM KHACHHANG K,DONDH D
	WHERE K.MAKH=D.MAKH
		AND NGAYDAT=@X

EXEC CAU1 '15/3/2004'

-- CAU 2: LIET KE DS KH(TENKH,DC)CO DAT HANG SAN PHAM CO MA SO X
CREATE PROC CAU2
@X CHAR(4)
AS
	SELECT TENKH,DIACHI
	FROM KHACHHANG K,DONDH D,SANPHAM S,CHITIETDDH CT
	WHERE K.MAKH=D.MAKH
		AND S.MASP=CT.MASP
		AND CT.SODDH=D.SODDH
		AND S.MASP=@X

EXEC CAU2 'SP05'
	
-- CAU 3: LIET KE DS KH(TENKH,DC)CO DAT HANG VOI SO TONG TIEN TREN X(1 DON)
CREATE PROC CAU3
@X FLOAT
AS
	SELECT TENKH,DIACHI,D.SODDH,SUM(SOLUONG*S.GIA)
	FROM KHACHHANG K,DONDH D,SANPHAM S,CHITIETDDH CT
	WHERE K.MAKH=D.MAKH
		AND S.MASP=CT.MASP
		AND CT.SODDH=D.SODDH
	GROUP BY K.MAKH,D.SODDH,TENKH,DIACHI
	HAVING SUM(SOLUONG*S.GIA)>@X

EXEC CAU3 0
DROP PROC CAU3

-- CAU 4: LIET KE DS KH(TENKH,DC)CO DAT HANG VOI SO TONG TIEN TREN X(TAT CA)
CREATE PROC CAU4
@X FLOAT
AS
	SELECT TENKH,DIACHI,SUM(SOLUONG*S.GIA)
	FROM KHACHHANG K,DONDH D,SANPHAM S,CHITIETDDH CT
	WHERE K.MAKH=D.MAKH
		AND S.MASP=CT.MASP
		AND CT.SODDH=D.SODDH
	GROUP BY K.MAKH,TENKH,DIACHI
	HAVING SUM(SOLUONG*S.GIA)>@X

EXEC CAU4 0
DROP PROC CAU4

-- CAU 5: LIET KE DS SAN PHAM(TENSP,GIATHANHSX,GIA)BAN LAI TREN X
CREATE PROC CAU5
@X FLOAT
AS
	SELECT TENSP,SUM(L.SOLUONG*NL.GIA)AS GIATANHSX,SP.GIA AS GIABAN
	FROM NGUYENLIEU NL,LAM L,SANPHAM SP
	WHERE SP.MASP=L.MASP
		AND NL.MANL=L.MANL
	GROUP BY SP.MASP,TENSP,SP.GIA
	HAVING (SP.GIA-SUM(L.SOLUONG*NL.GIA))>@X

EXEC CAU5 0		

-- CAU 6: LIET KE DS KH(TENKH,DC)DA TREN X NGAY ROI CHUA DAT HANG
CREATE PROC CAU6
@D INT,@M INT,@Y INT
AS
	SELECT TENKH,DIACHI
	FROM KHACHHANG K,DONDH D
	WHERE K.MAKH=D.MAKH
	GROUP BY K.MAKH,TENKH,DIACHI
	HAVING (DAY(GETDATE())-DAY(MAX(NGAYDAT)))>@D
		AND (MONTH(GETDATE())-MONTH(MAX(NGAYDAT)))>@M
		AND (YEAR(GETDATE())-YEAR(MAX(NGAYDAT)))>@Y

EXEC CAU6 2,1,4
DROP PROC CAU6

CREATE PROC CAUF2
@X INT
AS
	SELECT TENKH,DIACHI,DATEDIFF(DD,MAX(NGAYDAT),GETDATE())
	FROM KHACHHANG K,DONDH D
	WHERE K.MAKH=D.MAKH
	GROUP BY K.MAKH,TENKH,DIACHI
	HAVING DATEDIFF(DD,MAX(NGAYDAT),GETDATE())>@X

EXEC CAUF2 4

-- CAU G7 LIET KE DS SP(TENSP,SODON)CO TONG SO DON DAT HANG TREN X
CREATE PROC CAU7
@X INT
AS 
	SELECT TENSP,COUNT(*)AS SODON
	FROM SANPHAM S,DONDH D,CHITIETDDH CT
	WHERE S.MASP=CT.MASP
		AND D.SODDH=CT.SODDH
	GROUP BY S.MASP,TENSP
	HAVING COUNT(*)>@X

EXEC CAU7 2

-- CAU 8: LIET KE DS SP(TENSP,TONGSL)CO TONG SO LUONG DAT HANG TREN X
CREATE PROC CAU8
@X INT
AS
	SELECT TENSP,SUM(SOLUONG)AS 'TONG SO LUONG'
	FROM SANPHAM S,CHITIETDDH CT
	WHERE CT.MASP=S.MASP
	GROUP BY S.MASP,TENSP
	HAVING SUM(SOLUONG)>@X 

EXEC CAU8 5

-- CAU 9: LIET KE DS SP(TENSP,TONG SO TIEN)CO TONG SO TIEN DAT HANG TREN X
CREATE PROC CAU9
@X FLOAT
AS
	SELECT TENSP,SUM(SOLUONG*GIA)AS 'TONG SO LUONG'
	FROM SANPHAM S,CHITIETDDH CT
	WHERE CT.MASP=S.MASP
	GROUP BY S.MASP,TENSP
	HAVING SUM(SOLUONG*GIA)>@X 

EXEC CAU9 8000000
