USE BAITAP5

------------ TRIGGER ----------
-- CAU 1: MOI NGAY KHACH HANG CHI DAT TOI DA 2 DON HANG
CREATE TRIGGER T1 ON DONDH
FOR INSERT,UPDATE
AS
IF EXISTS(SELECT MAKH,NGAYDAT
			FROM DONDH
			GROUP BY MAKH,NGAYDAT
			HAVING COUNT(*)>2)
BEGIN
	PRINT 'MOI NGAY CHI DAT TOI DA 2 DON HANG'
	ROLLBACK TRAN
END

DROP TRIGGER T1
INSERT INTO DONDH
VALUES('DH009','15/03/2004','KH001');

-- CAU 2: MOI DON DAT HANG CO TONG SO LUONG SAN PHAM KHONG QUA 100
CREATE TRIGGER T2 ON CHITIETDDH
FOR INSERT,UPDATE
AS
IF EXISTS(SELECT SODDH
			FROM CHITIETDDH
			GROUP BY SODDH
			HAVING SUM(SOLUONG)>100)
BEGIN
	PRINT 'MOI DON DAT HANG CO TONG SO LUONG SAN PHAM KHONG QUA 100'
	ROLLBACK TRAN
END

INSERT INTO ChiTietDDH
	VALUES('DH006','SP03',600);
DROP TRIGGER T2


-- CAU 3: DAM BAO RANG MOI SAN PHAM KHONG BI LO HON 50%
CREATE TRIGGER T3 ON SANPHAM
FOR INSERT,UPDATE
AS
IF EXISTS(SELECT S.MASP
		FROM SANPHAM S,NGUYENLIEU N,LAM L
		WHERE N.MANL=L.MANL
			AND L.MASP=S.MASP
		GROUP BY S.MASP,TENSP,S.GIA
		HAVING ((SUM(SOLUONG*N.GIA)-S.GIA)/SUM(SOLUONG*N.GIA)*100)>50)
BEGIN
	PRINT 'DAM BAO RANG MOI SAN PHAM KHONG BI LO HON 50%'
	ROLLBACK TRAN
END

CREATE TRIGGER T4 ON NGUYENLIEU
FOR INSERT,UPDATE
AS
IF EXISTS(SELECT S.MASP
		FROM SANPHAM S,NGUYENLIEU N,LAM L
		WHERE N.MANL=L.MANL
			AND L.MASP=S.MASP
		GROUP BY S.MASP,TENSP,S.GIA
		HAVING ((SUM(SOLUONG*N.GIA)-S.GIA)/SUM(SOLUONG*N.GIA)*100)>50)
BEGIN
	PRINT 'DAM BAO RANG MOI SAN PHAM KHONG BI LO HON 50%'
	ROLLBACK TRAN
END

CREATE TRIGGER T5 ON LAM
FOR INSERT,UPDATE
AS
IF EXISTS(SELECT S.MASP
		FROM SANPHAM S,NGUYENLIEU N,LAM L
		WHERE N.MANL=L.MANL
			AND L.MASP=S.MASP
		GROUP BY S.MASP,TENSP,S.GIA
		HAVING ((SUM(SOLUONG*N.GIA)-S.GIA)/SUM(SOLUONG*N.GIA)*100)>50)
BEGIN
	PRINT 'DAM BAO RANG MOI SAN PHAM KHONG BI LO HON 50%'
	ROLLBACK TRAN
END

DROP TRIGGER T5


